version: '3.7'

services:
  pantry:
    image: pantry
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PORT=${PORT}
      target: base
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    ports:
      - 3001:${PORT}
    env_file:
      - .env
    command: npm run dev
