version: '3.7'

services:
  pantry:
    image: pantry
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PORT=${PORT}
      target: base
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: pantry-docker
    ports:
      - 3001:${PORT}
    env_file:
      - .env
    command: npm run dev
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'pantry'
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - pantry-db:/var/lib/mysql
volumes:
  pantry-db:
